dataset:
  num_edge_points: 512
  num_points_reg: 256
  num_mv_vecs: 5
  use_data_augmentation: true
  multi_rel: true
  num_max_edge: -1
  all_edges: true
  padding: 0.2
  seed: 2025
  relpts: "obj_only"

train:
  ckp_path: ./model_checkpoints/obj_encoder.pth
  name: GAT
  epoch: 1000
  log_interval: 5
  evaluation_interval: 5
  save_interval: 10
  batch_size: 8
  workers: 8
  wandb_path: ./wandb
  wandb_project: Geo_MGAT
  none_ratio: 0.1
  drop_out: 0.3
  verbose: true
  meter: average
  scheduler: 'cosine'
  num_negative_sample: 8
  sampler: 'frequency'
  freq_temperature: 0.3 # 0.5, 2
  loss_temperature: 0.3
  lambda_obj: 0.1
  lambda_rel: 1.0
  lambda_geo: 1.0
  lambda_view: 1.0
  oversampling: false
  seed: 42

model:
  num_graph_update: 2 # 1
  layers: 50
  dim_edge_feats: 512
  dim_obj_feats: 512
  dim_geo_feats: 11 
  dim_attn: 512
  num_heads: 8
  use_rgb: true
  use_normal: true
  flow: target_to_source
  num_layers: 8
  relation_type: "vlsat"
  edge_attention: false
  gat_type: "bidirectional"
  use_distance_mask: true

optimizer:
  learning_rate: 0.0001
  weight_decay: 0.0001