dataset:
  num_edge_points: 512
  num_points_reg: 256
  use_data_augmentation: true
  multi_rel: true
  num_max_edge: -1
  all_edges: true
  padding: 0.2
  seed: 2025

train:
  ckp_path: ./model_checkpoints/pc_encoder_vl.pth
  name: GAT
  epoch: 1000
  log_interval: 20
  evaluation_interval: 10
  save_interval: 20
  batch_size: 32
  workers: 4
  wandb_path: ./wandb
  wandb_project: bfeat_sg_skip_obj
  none_ratio: 0.1
  drop_out: 0.5
  verbose: true
  meter: average
  num_negative_sample: 16
  freq_temperature: 0.4

model:
  num_graph_update: 2
  layers: 50
  dim_edge_feats: 512
  dim_obj_feats: 512
  dim_geo_feats: 11 
  dim_attn: 512
  num_heads: 8
  use_rgb: true
  use_normal: true
  flow: target_to_source

optimizer:
  learning_rate: 0.001
  weight_decay: 0.0001