from runners.trainer import BFeatVanillaTrainer
from runners.trainer_jjam import BFeatJjamTongTrainer
from runners.trainer_rel_ssl import BFeatRelSSLTrainer
from runners.trainer_skip_obj import BFeatSkipObjTrainer
from runners.trainer_rel_only import BFeatRelOnlyContrasTrainer