dataset:
  num_edge_points: 512
  num_points_reg: 256
  num_mv_vecs: 5
  use_data_augmentation: true
  multi_rel: true
  num_max_edge: -1
  all_edges: true
  padding: 0.2
  seed: 2025

train:
  ckp_path: ./model_checkpoints/pc_encoder_vl.pth
  name: GAT
  epoch: 1000
  log_interval: 5
  evaluation_interval: 5
  save_interval: 20
  batch_size: 8
  workers: 8
  wandb_path: ./wandb
  wandb_project: bfeat_sg_jjam_gcn
  none_ratio: 0.1
  drop_out: 0.5
  verbose: true
  meter: average
  scheduler: 'cyclic'
  num_negative_sample: 8
  sampler: 'frequency'
  freq_temperature: 0.3
  loss_temperature: 0.3
  lambda_obj: 0.1
  lambda_rel: 1.0
  lambda_con: 1.0
  lambda_obj_con: 1.0

model:
  num_graph_update: 2
  layers: 50
  dim_edge_feats: 512
  dim_obj_feats: 512
  dim_geo_feats: 11 
  dim_attn: 512
  num_heads: 8
  use_rgb: true
  use_normal: true
  flow: target_to_source
  num_layers: 9
  relation_type: "pointnet"

optimizer:
  learning_rate: 0.001
  weight_decay: 0.0001